### ISSUE TITLE
Dio requests crash iOS app with Flutter 2.0.x

### ISSUE THREAD

**Issue by faustinoribeiro** [flutterchina/dio#1085]
### New Issue Checklist

- [ X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

Platform: ios
Platform Version: 10.3.4
Flutter version: 2.0.2
Dio Version:  3.0.10
Android Studio: 4.1.2
Xcode Version: 
Repro rate: 100%
Repro with our demo prj: not tested (can test later if needed)

### Issue Description and Steps

The app crashes as soon a dio request is performed. This happens only in release mode with version 2.0.2 of Flutter (and perhaps any 2.0.x version), stable channel.

Switching to dev channel solves the issue (but I's rather stay on stable).

Steps:
- Make sure version 2.0.2 of Flutter is active (stable channel)
- Create default Flutter app in Android Studio (counter app)
- Replace ```onPressed:  _incrementCounter``` call with:
```
onPressed: () async {
  final dio = Dio();
  final response = await dio.get("https://google.com");
  print(response);
}
```
- compile app for production and launch on real iPhone device
- Tap + floating button to trigger dio request

On my iPhone 5, running the app through XCode, I get the following error:

```
libobjc.A.dylib`objc_msgSend:
    0x1a5acdc0 <+0>:  cbz    r0, 0x1a5acdfe            ; <+62>
    0x1a5acdc2 <+2>:  ldr.w  r9, [r0]
->  0x1a5acdc6 <+6>:  ldrh.w r12, [r9, #0xc] = DartWorker (21): EXC_BAD_ACCESS (code=1, address=0x1000000c)
    0x1a5acdca <+10>: ldr.w  r9, [r9, #0x8]
    0x1a5acdce <+14>: and.w  r12, r12, r1
    0x1a5acdd2 <+18>: add.w  r9, r9, r12, lsl #3
    0x1a5acdd6 <+22>: ldr.w  r12, [r9]
    0x1a5acdda <+26>: teq.w  r12, r1
    0x1a5acdde <+30>: bne    0x1a5acde6                ; <+38>
    0x1a5acde0 <+32>: ldr.w  r12, [r9, #0x4]
    0x1a5acde4 <+36>: bx     r12
    0x1a5acde6 <+38>: cmp.w  r12, #0x1
    0x1a5acdea <+42>: blo    0x1a5acdf8                ; <+56>
    0x1a5acdec <+44>: it     eq
    0x1a5acdee <+46>: ldreq.w r9, [r9, #0x4]
    0x1a5acdf2 <+50>: ldr    r12, [r9, #8]!
    0x1a5acdf6 <+54>: b      0x1a5acdda                ; <+26>
    0x1a5acdf8 <+56>: ldr.w  r9, [r0]
    0x1a5acdfc <+60>: b      0x1a5ad1a0                ; <redacted>
    0x1a5acdfe <+62>: mov.w  r1, #0x0
    0x1a5ace02 <+66>: mov.w  r2, #0x0
    0x1a5ace06 <+70>: mov.w  r3, #0x0
    0x1a5ace0a <+74>: bx     lr
    0x1a5ace0c <+76>: nop    
    0x1a5ace0e <+78>: nop    
    0x1a5ace10 <+80>: nop    
    0x1a5ace12 <+82>: nop    
    0x1a5ace14 <+84>: nop    
    0x1a5ace16 <+86>: nop    
    0x1a5ace18 <+88>: nop    
    0x1a5ace1a <+90>: nop    
    0x1a5ace1c <+92>: nop    
    0x1a5ace1e <+94>: nop  
```
Running the app directly on the phone simply crashes the app (the app reboots).

pubspec.yaml:
```
name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

**Comment by faustinoribeiro** [comment]
Issue seems to have been fixed with upgrade to stable channel 2.0.3.
Will conduct additional tests, but so far so good.

**Comment by jmysliv** [comment]
I'm still having this issue. Upgrading Flutter to 2.0.3 didn't help.

**Comment by fight123** [comment]
How to fix?On ios 10.3,it crash.
