### ISSUE TITLE
flutter: Content size below specified contentLength.  511 bytes written but expected 704.

### ISSUE THREAD

**Issue by waqaryounusjatt788** [flutterchina/dio#781]
Hi, I am facing these issue while I'm sending text file to server by using bio 3.0.9

**Comment by willieprinsloo** [comment]
HttpException: Content size below specified contentLength.  6719 bytes written but expected 8635

Also experiencing a similar issue:

  Directory tempDir = await getTemporaryDirectory();
  File outputFile = await File ('${tempDir.path}/flutter_sound-tmp.aac');
  Dio dio = new Dio();
  FormData formData = new FormData.fromMap({
    "file": await MultipartFile.fromFile(outputFile.path,filename:"file"),
  });
  Response  response = await dio.put("http://10.0.2.2:5000/uploader", data: formData);
  print (response.toString());

**Comment by sayhicoelho** [comment]
same issue here

**Comment by sayhicoelho** [comment]
I've fixed the upload and its progress after a few hours.

Code:

```dart
static Future<Response> upload<T>(
  String url,
  Future<Uint8List> file,
  String fileName,
  {
    String imageType = 'jpeg',
    Map data = const {},
    void Function(int, int) onSendProgress,
  }
) async {
  var fileStream = file.asStream().asBroadcastStream();
  var fileBytes = (await fileStream.toList())[0];
  var fileSize = fileBytes.length;

  var formData = FormData.fromMap({
    ...data,
    'file': MultipartFile(
      Stream.fromIterable(fileBytes.map((e) => [e])),
      fileSize,
      filename: fileName,
      contentType: MediaType('image', imageType)
    ),
  });

  var options = Options(
    headers: {
      Headers.contentLengthHeader: formData.length,
    }
  );

  return _dio.post<T>(
    url,
    data: formData,
    options: options,
    onSendProgress: onSendProgress,
  );
}
```

**Comment by thanhdatvo** [comment]
Using MultipartFile.fromFile() doesn’t resolve the issue completely. 
The problem occurs intermittently
